### ISSUE TITLE
This is an issue!

### ISSUE THREAD

**Issue by jemurrayPhD** [KatherineSmee/katherine-math#2]
I found a bug, there are no feet pics in this repo.

**Comment by jemurrayPhD** [comment]
I've assigned @KatherineSmee and myself as Assignee's, so it's our job to address this issue.

**Comment by jemurrayPhD** [comment]
This issue has now been resolved!

**Comment by KatherineSmee** [comment]
Uh oh

On Mar 10, 2024, at 23:14, jemurrayPhD ***@***.***> wrote:

﻿

I found a bug, there are no feet pics in this repo.
